name: manualTriggered
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
env:
  cloud: google-cloud 

on:
  workflow_dispatch:
    inputs:
      number1:
        description: 'First Number'
        default: '0'
        required: true
      number2:
        description: 'Second Number'
        default: '0'
        required: true

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      Greeting: hello

    steps:
      - name: Add numbers
        id: sum
        # Redirection (>> $GITHUB_OUTPUT) is mandatory to share outputs between steps
        run: echo "sum=$(( ${{ github.event.inputs.number1 }} + ${{ github.event.inputs.number2 }} ))" >> $GITHUB_OUTPUT
     
      - name: Display sum
        run: echo "The sum of ${{ github.event.inputs.number1 }} and ${{ github.event.inputs.number2 }} is ${{ steps.sum.outputs.sum }}"
